#!/usr/bin/env php
<?php

require_once __DIR__ . '/vendor/autoload.php';
require_once __DIR__ . '/vendor/ivandowhai/light-framework/src/Autoloader.php';

use Light\ {
    Autoloader,
    Console\Registry,
    Console\ConsoleHandler,
    DependenciesLoader
};

spl_autoload_register(new Autoloader());

$registry = new Registry();

$defaultCommands = require_once __DIR__ . '/commands.php';

foreach ($defaultCommands as $name => $class) {
    $registry->addCommand($name, $class);
}

$commandHandler = new ConsoleHandler($registry, new DependenciesLoader());

$commandHandler->run($argv);
