#!/usr/bin/env php
<?php

require_once __DIR__ . '/vendor/autoload.php';

use Light\ {
    Console\Registry,
    Console\ConsoleHandler,
    DependenciesLoader
};

$registry = new Registry();

$defaultCommands = require_once __DIR__ . '/commands.php';

foreach ($defaultCommands as $name => $class) {
    $registry->addCommand($name, $class);
}

$commandHandler = new ConsoleHandler($registry, new DependenciesLoader());

try {
    $commandHandler->run($argv);
} catch (\Exception $exception) {
    echo $exception->getMessage();
}

