name: PHP Composer

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Composer intall
      run: composer install
    - name: phpstan
      run: vendor/bin/phpstan analyse src -l 6
    - name: PHPUnit
      run: php vendor/bin/phpunit tests
